"""
BATUHAN — Document Storage Abstraction Layer.

Provides a unified interface for storing and retrieving audit documents.
Supports two backends:
  - "local": filesystem storage under settings.storage_base_path
  - "s3": S3-compatible object storage (Cloudflare R2)

All upload/download handlers should use these functions instead of
direct filesystem operations.

Key design:
  - upload() returns a reference string:
    - Local: relative path like "shared_docs/abc123/file.docx"
    - S3: "s3://bucket/shared_docs/abc123/file.docx"
  - is_s3_ref(ref) checks if a reference is S3-based (None-safe)
  - ensure_local(ref) returns an absolute local filesystem path:
    - For local refs: resolves to absolute path under storage_base_path
    - For S3 refs: downloads to cache dir, returns cache path
  - resolve_docx_key(ref) returns the local path that doc_converter
    stores in DocumentSignatureField.docx_path — use this for all
    DSF queries to stay consistent.
  - Old file_path values (absolute local paths) are handled by
    ensure_local() as a backward-compatibility fallback
"""
from __future__ import annotations

import logging
import os
import shutil
from pathlib import Path

import boto3
from botocore.config import Config as BotoConfig
from botocore.exceptions import ClientError

from config.settings import get_settings

logger = logging.getLogger(__name__)

_S3_PREFIX = "s3://"


# ---------------------------------------------------------------------------
# S3 client singleton
# ---------------------------------------------------------------------------

_s3_client = None


def _get_s3_client():
    """Lazy-initialised boto3 S3 client for R2."""
    global _s3_client
    if _s3_client is not None:
        return _s3_client
    settings = get_settings()
    if not settings.s3_endpoint_url:
        raise RuntimeError(
            "STORAGE_BACKEND=s3 but S3_ENDPOINT_URL is not configured"
        )
    _s3_client = boto3.client(
        "s3",
        endpoint_url=settings.s3_endpoint_url,
        aws_access_key_id=settings.s3_access_key,
        aws_secret_access_key=settings.s3_secret_key,
        region_name=settings.s3_region or "auto",
        config=BotoConfig(
            signature_version="s3v4",
            retries={"max_attempts": 3, "mode": "standard"},
        ),
    )
    return _s3_client


# ---------------------------------------------------------------------------
# Reference helpers
# ---------------------------------------------------------------------------

def is_s3_ref(ref: str | None) -> bool:
    """Check if a file reference points to S3 storage. None-safe."""
    if not ref:
        return False
    return ref.startswith(_S3_PREFIX)


def _parse_s3_ref(ref: str) -> tuple[str, str]:
    """Parse 's3://bucket/key' into (bucket, key)."""
    without_prefix = ref[len(_S3_PREFIX):]
    bucket, _, key = without_prefix.partition("/")
    return bucket, key


def _object_key_from_relative(relative_path: str) -> str:
    """Normalise a relative path into a clean S3 object key."""
    return relative_path.replace("\\", "/").lstrip("/")


def _cache_path_for_key(object_key: str) -> str:
    """Deterministic local cache path for an S3 object key."""
    settings = get_settings()
    cache_dir = settings.local_storage_cache_dir
    return os.path.join(cache_dir, object_key)


def _clear_cached_files(object_key: str) -> None:
    """Remove the local cached DOCX and its sibling PDF for an object key."""
    cached = _cache_path_for_key(object_key)
    if os.path.isfile(cached):
        os.remove(cached)
    # Also remove sibling PDF (generated by LibreOffice during /prepare)
    cached_pdf = os.path.splitext(cached)[0] + ".pdf"
    if os.path.isfile(cached_pdf):
        os.remove(cached_pdf)


# ---------------------------------------------------------------------------
# Core API
# ---------------------------------------------------------------------------

def upload(
    relative_path: str,
    content: bytes,
    *,
    content_type: str = "application/octet-stream",
) -> str:
    """Upload file content and return a storage reference.

    Args:
        relative_path: path relative to storage root, e.g.
                        "shared_docs/{audit_set_id}/{filename}"
        content: raw file bytes
        content_type: MIME type hint for S3

    Returns:
        Storage reference string:
          - Local mode: the relative_path itself
          - S3 mode: "s3://{bucket}/{object_key}"

    In S3 mode, verifies the object exists after upload via head_object.
    Also clears any locally cached copy (and sibling PDF) so subsequent
    ensure_local() calls fetch the fresh version.
    """
    settings = get_settings()
    object_key = _object_key_from_relative(relative_path)

    if settings.storage_backend == "s3":
        client = _get_s3_client()
        bucket = settings.s3_bucket
        client.put_object(
            Bucket=bucket,
            Key=object_key,
            Body=content,
            ContentType=content_type,
        )
        # Verify the object was persisted
        client.head_object(Bucket=bucket, Key=object_key)
        ref = f"{_S3_PREFIX}{bucket}/{object_key}"
        logger.info("[STORAGE] Uploaded to S3: %s (%d bytes)", ref, len(content))
        # Clear local cache so ensure_local() fetches the new version
        _clear_cached_files(object_key)
        return ref
    else:
        # Local filesystem
        abs_path = os.path.join(settings.storage_base_path, object_key)
        os.makedirs(os.path.dirname(abs_path), exist_ok=True)
        with open(abs_path, "wb") as f:
            f.write(content)
        logger.info("[STORAGE] Uploaded to local: %s (%d bytes)", object_key, len(content))
        return object_key


def exists(ref: str) -> bool:
    """Check whether a stored object exists."""
    if is_s3_ref(ref):
        bucket, key = _parse_s3_ref(ref)
        try:
            _get_s3_client().head_object(Bucket=bucket, Key=key)
            return True
        except ClientError:
            return False
    else:
        local_path = _resolve_local_path(ref)
        return os.path.isfile(local_path)


def download(ref: str) -> bytes:
    """Download file content from storage."""
    if is_s3_ref(ref):
        bucket, key = _parse_s3_ref(ref)
        resp = _get_s3_client().get_object(Bucket=bucket, Key=key)
        return resp["Body"].read()
    else:
        local_path = _resolve_local_path(ref)
        with open(local_path, "rb") as f:
            return f.read()


def ensure_local(ref: str) -> str:
    """Return an absolute local filesystem path for the given reference.

    - For S3 refs: downloads to cache dir if not already cached
    - For local refs: resolves to absolute path under storage_base_path
    - For legacy absolute paths: returns as-is

    This is the primary read path for viewer, PDF converter, flattener,
    and any code that needs a local file path.
    """
    if is_s3_ref(ref):
        bucket, key = _parse_s3_ref(ref)
        cached = _cache_path_for_key(key)
        if not os.path.isfile(cached):
            os.makedirs(os.path.dirname(cached), exist_ok=True)
            logger.info("[STORAGE] Cache miss — downloading %s", ref)
            _get_s3_client().download_file(bucket, key, cached)
        return os.path.abspath(cached)
    else:
        return os.path.abspath(_resolve_local_path(ref))


def resolve_docx_key(ref: str) -> str:
    """Return the local path that doc_converter.prepare_document() uses as
    DocumentSignatureField.docx_path.

    This is the canonical key for all DSF queries — use it instead of
    constructing the path manually. It mirrors what ensure_local() returns
    (an absolute local path) so it matches what prepare_document() stores.
    """
    return ensure_local(ref)


def delete(ref: str) -> None:
    """Delete a stored object. Silently ignores missing objects."""
    if is_s3_ref(ref):
        bucket, key = _parse_s3_ref(ref)
        try:
            _get_s3_client().delete_object(Bucket=bucket, Key=key)
        except ClientError:
            pass
        # Also remove from local cache (DOCX + sibling PDF)
        _clear_cached_files(key)
    else:
        local_path = _resolve_local_path(ref)
        if os.path.isfile(local_path):
            os.remove(local_path)


def invalidate_cache(ref: str) -> None:
    """Remove the local cache copy of an S3 object (e.g. after regeneration).
    Also removes the sibling PDF so the viewer re-converts on next access."""
    if is_s3_ref(ref):
        _, key = _parse_s3_ref(ref)
        _clear_cached_files(key)


# ---------------------------------------------------------------------------
# Resolve local paths (backward compat)
# ---------------------------------------------------------------------------

def _resolve_local_path(ref: str) -> str:
    """Convert a storage reference to an absolute local filesystem path.

    Handles three cases:
      1. Already absolute (legacy): "/data/storage/shared_docs/..." → as-is
      2. Relative with storage_base_path prefix: "./storage/shared_docs/..." → abspath
      3. Pure relative key: "shared_docs/..." → join with storage_base_path
    """
    if os.path.isabs(ref):
        return ref
    settings = get_settings()
    if ref.startswith(settings.storage_base_path):
        return os.path.abspath(ref)
    return os.path.abspath(os.path.join(settings.storage_base_path, ref))


# ---------------------------------------------------------------------------
# Health check helper
# ---------------------------------------------------------------------------

def health_check() -> dict:
    """Write a test object, read it back, verify, delete. Returns status dict."""
    settings = get_settings()
    if settings.storage_backend != "s3":
        return {"backend": "local", "status": "skipped", "detail": "Not using S3"}

    test_key = "_health_check/probe.txt"
    test_body = b"certiva-storage-health-check"
    try:
        client = _get_s3_client()
        bucket = settings.s3_bucket

        # Write
        client.put_object(Bucket=bucket, Key=test_key, Body=test_body)

        # Read back
        resp = client.get_object(Bucket=bucket, Key=test_key)
        read_back = resp["Body"].read()

        # Verify
        if read_back != test_body:
            return {
                "backend": "s3",
                "status": "FAIL",
                "detail": "Read-back mismatch",
            }

        # Delete
        client.delete_object(Bucket=bucket, Key=test_key)

        return {
            "backend": "s3",
            "bucket": bucket,
            "endpoint": settings.s3_endpoint_url,
            "status": "OK",
        }
    except Exception as e:
        return {
            "backend": "s3",
            "status": "FAIL",
            "detail": str(e),
        }
